// Auto-generated by PWA builder script.
importScripts('https://storage.googleapis.com/workbox-cdn/releases/7.0.0/workbox-sw.js');

if (workbox) {
    console.log(`Workbox is loaded.`);
    
    // This message listener waits for a command from the web page to activate.
    self.addEventListener('message', (event) => {
      if (event.data && event.data.type === 'SKIP_WAITING') {
        console.log('Service Worker received SKIP_WAITING message, activating now.');
        self.skipWaiting();
      }
    });

    workbox.precaching.precacheAndRoute([
    {
        "url": "icon-72.png",
        "revision": "d7e2fea916659bbf271b4632f028fed5"
    },
    {
        "url": "icon-96.png",
        "revision": "f1bdf68dd999551760088eb79f5cbcba"
    },
    {
        "url": "icon-128.png",
        "revision": "1ec8980d1a4a78149a5ec7aac0a52a79"
    },
    {
        "url": "icon-144.png",
        "revision": "70839b0a9ce56b64a72ca87b9c29f139"
    },
    {
        "url": "icon-152.png",
        "revision": "24fd20976f6dc6d81b99bdecd571fced"
    },
    {
        "url": "icon-192.png",
        "revision": "286958b45be08bdc916b8e3126b2203d"
    },
    {
        "url": "icon-384.png",
        "revision": "d3d46f60ff5014f7d85d047e1c55329f"
    },
    {
        "url": "icon-512.png",
        "revision": "1a98134a086859d517de611e9e0579bc"
    },
    {
        "url": "build pwa make html app offline and installable yasin best working re-run this for updates.py",
        "revision": "2fc7c1c94e2f15173083ebeda834d953"
    },
    {
        "url": "Copy of index.html",
        "revision": "a5802af42585a19e78f604bc0af1b0a5"
    },
    {
        "url": "index.html",
        "revision": "a5802af42585a19e78f604bc0af1b0a5"
    },
    {
        "url": "manifest.json",
        "revision": "35e148eb5d0b0ac39913f8b13a2bc468"
    },
    {
        "url": "my reminder app.html",
        "revision": "0a7843b220cd0ec7beff6a5ce0f1c09d"
    },
    {
        "url": "offline.html",
        "revision": "986de93949013e958b0e14acd85491cd"
    },
    {
        "url": "README.md",
        "revision": "1dfaf6c7e47027f9d4a6d348f4a4b14b"
    },
    {
        "url": "sw.js",
        "revision": "fadefee9f81e721fead9fb669aa1c4d4"
    }
]);

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'style' || request.destination === 'script',
        new workbox.strategies.StaleWhileRevalidate({ cacheName: 'asset-cache' })
    );

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'image',
        new workbox.strategies.CacheFirst({
            cacheName: 'image-cache',
            plugins: [ new workbox.expiration.ExpirationPlugin({ maxEntries: 60, maxAgeSeconds: 30 * 24 * 60 * 60 }) ],
        })
    );

    workbox.routing.setCatchHandler(async ({event}) => {
        if (event.request.destination === 'document') {
            return await caches.match('offline.html') || Response.error();
        }
        return Response.error();
    });

} else {
    console.log(`Workbox failed to load.`);
}